# Generated by Django 3.1.3 on 2021-07-31 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_no', models.IntegerField()),
                ('is_done', models.BooleanField(default=False)),
                ('remarks', models.TextField()),
                ('mission_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mission.missions')),
            ],
        ),
    ]
